/**
 * film/pages/intro.js — **引子（帧 0–419）的页面内容与算术**（Phase 5 / R1）。
 *
 * 这个文件只产出**纯数据与纯函数**：没有 DOM、没有 `fs`、没有 `Date`。
 * 组装成 HTML 是 `body.js` 的事，截图是 `shot.mjs` 的事。
 *
 * ## 三拍（`design-options.md` §1 / §4.14，边界与 `engine/content.js` 的 `PRELUDE_MARKS` 一致）
 *
 * | 拍 | 帧 | 时间 | 内容 |
 * |---|---|---|---|
 * | 1 注入 | 0–143 | 6.00 s | context 注入：前言先滚过去，然后是一份**为片子写的** context 文档 |
 * | 2 思考 | 144–250 | 4.46 s | 思维链：**生成到一半的英文**（不是乱码），其中一句歌词成形 1.5 s |
 * | 3 输出 | 251–418 | 7.00 s | 一段很用力的长回复，**在第 419 帧完成** |
 * | 之后 | 419– | — | 引子结束：**画面冻结在完成态**（第一幕的画面另有其人负责） |
 *
 * ## 行网格（为什么要有它）
 *
 * 滚动区整个是**一列固定 24 px 的行**（`.stage__line`，由 `body.js` 的 CSS 定义）。
 * 这不是洁癖，是**让「滚动位置 = f(t)」可被证明**：
 *
 * - 内容高 = `24 × 已显示行数` + 一点点块内边距 → 我能在**没有浏览器**的情况下算出
 *   「本帧最多能滚到哪」，于是 `want ≤ maxScroll` 是一条**单元测试**，不是一次目测。
 * - 逐帧页面最怕的是「设了 `scrollTop` 但内容不够高 → 被浏览器夹住」，
 *   那样画面会静止而**没有任何报错**（`AGENTS.md` §8 的空白帧同款陷阱）。
 *
 * 行的排版纪律（`AGENTS.md` §7「排版自己算」的网页版）：
 * 每行**硬换行**、`white-space:pre`、行盒 `overflow:hidden` —— 超长的行会被**裁掉**而不是折行，
 * 折行会让高度从 24 变成 48，整个算术崩掉。所以 `lineBudget()` 里有一条**字符预算测试**守着它。
 *
 * ## 现在**没有**做的事（如实记账）
 *
 * - 注入是「流过去 + 追底」还是「逐字吐」——⛔ 未拍板，这里取**追底**（内容逐行出现，
 *   滚动位置跟着最新一行，等价于真实聊天窗口的 auto-follow）。理由：它同时满足 §1 的
 *   「前言先滚过去」和 §1.6 的「每帧直接设滚动位置」，且**不依赖任何布局测量**。
 * - 「糊」不在这一层：浏览器出**清晰的真排版**，模糊由后期做（§1.6）。
 * - 那段 context 文档**不是本仓库的 `AGENTS.md`**，是一份为片子写的文件（§1.8）。
 */

import { FPS, FRAME_COUNT, timeAt } from '../engine/clock.js';

/**
 * 引子的拍点（帧号）。**必须与 `film/engine/content.js` 的 `PRELUDE_MARKS` 一致** ——
 * 两处不一致就等于「时间轴断言」在骗自己。`film/test/pages.test.js` 里有一条测试盯着这件事。
 */
export const MARKS = { inject: 0, think: 144, output: 251, firstLyric: 419 };

/** 行网格的行高（px）。**唯一来源** —— CSS 里那份由 `body.js` 从这里取值。 */
export const LINE_H = 24;

/** 固定区的行数：`Instructions from` 一条 + 三行署名 + `You are a …` 一条。 */
export const FIXED_LINES = 5;

/** 固定区的上下内边距（px）。 */
export const FIXED_PAD = 12;

/** 固定区的总高（px）。**它必须是个能算出来的数**，否则滚动窗口高就无从谈起。 */
export const FIXED_HEIGHT = FIXED_LINES * LINE_H + 2 * FIXED_PAD;

/**
 * 输入框那一条的高度（px）。**实测出来的**，不是猜的。
 *
 * 真界面在 960×640 下量到的是 `uV2eYG_card` = **712×114**（hero 态，输入区 min-height 52）。
 * 我们不是 hero 态（会话里已经有内容了），输入区是 dsh 的常规 `min-height:36px`，
 * 所以卡片矮一截：**R1 页面里实测 `uV2eYG_card` = 712×98**（= 8 上内边距 + 输入区 36 + 底排 42 + 12），
 * 加上卡片下方 8px 呼吸 → **106**。这个常量由 `shot.mjs --intro-scroll-check` 里那条
 * 「输入框实测高 == COMPOSER_HEIGHT」断言守着（改 CSS 就会红）。
 *
 * 之所以要它：滚动窗口高 = 舞台高 − 固定区 − 输入框，**三个都必须是常数**，
 * 否则「滚动位置 = f(t)」的算术就不成立了（`AGENTS.md` §7「排版自己算」）。
 */
export const COMPOSER_HEIGHT = 106;

/** 思维链那块 `.lcKema_thinkBody` 自带的上下内边距（`padding:4px 0 …`）。 */
export const THINK_BODY_PAD = 8;

/**
 * 思维链的**表头也占一格网格**（`.lcKema_row` 被包在一个 24 px 的 `.stage__line` 里）。
 *
 * ⚠️ 这条是实测出来的，不是想当然：表头**不**包网格时，它的高度由行盒内部决定 ——
 * `▾` 这个字形来自回退字体，行盒算出 **23 px**（不是 24）。
 * 于是「内容高 = 24 × 行数」在思维链那一块上差 23 px，滚动位置就跟着差，
 * 最后两行歌词被推到窗口外面去了（`shot.mjs --intro-scroll-check` 抓到）。
 * 教训照旧：**网页上的高度也要自己算**，不要让字体度量替你做布局决定。
 */
export const THINK_HEAD_LINES = 1;

/**
 * 一行能放多少「半角字符宽」。超出预算的行会被 `overflow:hidden` **裁掉**（见文件头）。
 * 14 px 的 Segoe UI 平均字宽约 6.4 px，`.dsh-col` 的内容宽是 760 − 48 = 712 px
 * → 约 111 字符；这里取 96 留出余量（不同字符宽度差很大，比如 `W` 与 `i`）。
 * 中日韩字符按 2 个半角宽计。
 */
export const LINE_BUDGET = 96;

// ─────────────────────────────────────────────────────────────────────────────
// 1. 内容（全部是常量；`n` 只决定「显示到第几行」）
// ─────────────────────────────────────────────────────────────────────────────

/**
 * 拍 1 的前言（`design-options.md` §1.5 的真实措辞，按行切开）。
 * ⚠️ §1 明确：这一句属于**滚动区**，先滚过去，**不进固定区**。
 * @type {readonly string[]}
 */
export const PREAMBLE = [
  'The following workspace instructions may be relevant to your work. Use them as guidance',
  'when applicable. More specific instructions take precedence over broader ones. They do not',
  'override system, developer, or direct user instructions.',
];

/**
 * 拍 1 的 context 文档。**为片子写的**，不是本仓库的 `AGENTS.md`（§1.8）。
 *
 * 写法约束：机器文本一律英文（§0 全局硬约束）、**不出现 emoji**（§1.8）、
 * 每行 ≤ `LINE_BUDGET`。开头两条 `Instructions from:` 行会被渲染成 dsh 的
 * 键值行（`.ZkiH0q_field`），其余是正文行。
 * @type {readonly string[]}
 */
export const CONTEXT_DOC = [
  '<system-reminder>',
  'Instructions from: ~/.dsh/AGENTS.md',
  '<user-global-instructions>',
  '',
  '# Working agreements',
  '- Prefer plain files over generated artefacts; every artefact must be rebuildable.',
  '- Never commit secrets, binaries or large media. Keep the repository small.',
  '- One chart, one legend: every figure is regenerated by a single command.',
  '- Report what you did not run, and why. Silence is not evidence.',
  '',
  '## Layout',
  '  atlas/     source tables and fingerprints',
  '  sim/       the simulation itself (engine, scenes, primitives)',
  '  tools/     one-off scripts, checked in and documented',
  '  render/    frame output; ignored by git, rebuildable from scratch',
  '',
  '## Commands',
  '  sim check                    environment and asset self-check',
  '  sim frames --range A B       write the frame manifest for a range',
  '  sim shoot --seconds N        deterministic stills, then pixel-compare',
  '  sim encode                   assemble the master',
  '',
  '## Conventions',
  '- The frame index is the only key: n = round(t * rate). Never invent a second one.',
  '- Simulation state crosses frames only as an explicit argument.',
  '- Randomness is seeded per frame. Nothing may read the wall clock.',
  '- Pin native dependencies exactly; a patch release can move a pixel.',
  '',
  '## Fixed constants',
  '  rate      24',
  '  width     1920',
  '  height    1080',
  '',
  '## Review',
  '- Two renders of the same frame must be identical, byte for byte.',
  '- A gap or an overlap in the schedule is a bug, not a style choice.',
  '- Boundary frames get looked at by a person: first, last, and every cut.',
  '',
  '## Known traps',
  '- A pipeline that ends early is indistinguishable from one that succeeded.',
  '- Rounding at the boundary costs a whole frame; measure the boundary, not the average.',
  '- Assets that resolve over the network are not assets.',
  '',
  '## Escalation',
  '- If a convention blocks you, say so in the report; do not quietly work around it.',
  '- If two documents disagree, the shorter one wins; then fix the longer one.',
  '',
  'Instructions from: AGENTS.md',
  '<project-instructions>',
  '',
  '# Project',
  '- This repository renders a fixed number of frames into a single master file.',
  '- Everything below the render directory is disposable.',
  '- The manifest is the contract: if a frame is not in it, the frame does not exist.',
  '',
  '## What the reviewer will ask',
  '- Did the frame count reconcile, exactly, with no holes?',
  '- Did the same frame render the same twice?',
  '- Which parts did you not run, and what would it take to run them?',
  '',
  '</system-reminder>',
];

/**
 * 拍 2 的思维链：**生成到一半的英文**（§1 明确「不是乱码」—— 损坏的语义留给崩坏段）。
 *
 * 其中**一句歌词偶而成形**（§1）：`LYRIC_LINES` 那两行。它们不在这里 ——
 * 而是在 `THINKING` 的 `LYRIC_AT` 位置插入，免得有人改了数组顺序就悄悄挪走歌词。
 * @type {readonly string[]}
 */
export const THINKING = [
  'The request is short, so the answer has to come from the material, not from the wording.',
  'Two halves: what is on the screen, and what is running behind it.',
  'Start with the interface, because it is the only part that can be measured.',
  'Three passes: inject, reason, answer. Each one needs its own clock.',
  'Nothing on screen may move before the thing it describes exists.',
  'If the injected block is the same every frame, then it is scenery, not a message.',
  'The interface has to be built, not photographed: no service in the loop.',
  'That means the styles have to be carried along, exactly, at the version we ship.',
  'Check the sizes first. A radius or a border width moves the whole grid.',
  'Then check the colors: a theme that is not applied looks like a theme that is wrong.',
  'Both halves should be measurable in the same units, or the comparison is decoration.',
  'Keep the machine text machine-shaped: paths, flags, exit codes, no prose.',
  'The human lines are the only ones allowed to be warm.',
  'Wait. That is a lyric, not a thought.',
  'Where did that come from? It is not in the brief.',
  'Put it back in the stream and keep going; it will land on its own frame.',
  'The answer should be long enough to be heavy and plain enough to be ignored.',
  'It must finish on the exact frame the voice starts, or the handover is a lie.',
  'Do not decorate the ending. The ending is the first word of the song.',
  'Mark the boundaries so the checks can see them: a gap is a bug, not a pause.',
  'Prefers a slow, provable pipeline over a fast one that guesses.',
  'If a number appears twice in the code, one of them is wrong.',
  'Enough. Write the answer.',
];

/** 歌词那两行（`design-options.md` §4.14 的例子：英文原句 + 中文译句）。 */
export const LYRIC_LINES = ['Every day we talk a little less', '每天我们说的话都在逐渐减少'];

/**
 * 歌词插在 `THINKING` 的哪一行**之前**。
 * 改这个数就是改「歌词什么时候成形」—— 它必须等于 `LYRIC_AT`，
 * 因为 `frameOfLineStart()` / `frameOfLineDone()` 要用它反推那一帧。
 */
export const LYRIC_AT = 14;

/**
 * 拍 3 的长回复：**像样的模型回复**（长、用力），观众不需要读（§1 / §1.8）。
 * 不是元评论 —— 它是一段真的在解决工程问题的回复。
 * @type {readonly string[]}
 */
export const ANSWER = [
  'Short answer: the frame count is off by two, and the cause is the audio, not the renderer.',
  '',
  'Here is what I measured, in order.',
  '',
  '1. The container reports a duration of 197.504 s. That number comes from the header, not',
  '   from the samples: the header still describes the untrimmed file, so every tool that',
  '   trusts it agrees with every other tool that trusts it — and all of them are wrong',
  '   about this particular file. Both the original and the trimmed file report the same',
  '   duration. That is the first clue: a trim that changes nothing is suspicious.',
  '',
  '2. Dividing that duration by the frame interval gives 4740.1 frames. The pipeline expects',
  '   4741. So the tail is being cut, and it is being cut by the muxer: when the video and',
  '   the audio are combined with the shortest-stream flag, the audio decides where the file',
  '   ends. Two frames sit past that point. They are rendered, written to disk, and then',
  '   dropped, silently, with a zero exit code.',
  '',
  '3. The fix is to stop letting the audio decide the length. Set the duration explicitly,',
  '   or better, pin the frame count. Then verify it: count the frames in the delivered',
  '   file and compare against the manifest. A pipeline that ends early and a pipeline that',
  '   succeeded must not be able to look the same.',
  '',
  'I also checked the two things you did not ask about:',
  '',
  '- The colour tags belong on the input side. Setting them on the output makes the encoder',
  '  advertise a space it was never given, and the delivered file is a little darker than',
  '  the master. Nobody notices until the two are side by side.',
  '- The master is lossless by construction, so the delivery copy has to be a separate file.',
  '  Trying to keep both properties in one artefact is how a master quietly becomes lossy.',
  '',
  'What I did not do:',
  '',
  '- I did not re-encode the whole film to prove the count. I rendered thirty frames at the',
  '  boundary and counted those. The boundary is where the bug lives; the average is where',
  '  bugs hide.',
  '- I did not test on the second machine. The encoder output is not byte-reproducible across',
  '  group-of-pictures boundaries, so that comparison would have to be made on the input',
  '  bytes rather than the output bytes. I have left a hook for it.',
  '',
  'If you want the whole thing provable end to end, the order is: hash the feed, count the',
  'frames, then look at the boundary frames with your own eyes. Everything else is a proxy.',
];

// ─────────────────────────────────────────────────────────────────────────────
// 2. 分块与几何
// ─────────────────────────────────────────────────────────────────────────────

/**
 * @typedef {Object} Block
 * @property {string} key
 * @property {string} label 报告里用的名字
 * @property {number} start 第一帧（含）
 * @property {number} end 最后一帧（含）—— **闭区间**，因为「第 419 帧完成」是闭的
 * @property {readonly string[]} lines 这个块的全部行（含插入的歌词）
 * @property {boolean} [thinkBody] 是否包在 `.lcKema_thinkBody` 里（多 8 px 内边距）
 */

/**
 * 文档的分块表。**顺序即文档顺序**。
 *
 * 几个数怎么来的：
 * - 前言 3 行给了 18 帧（0.75 s）—— §1 说它「先滚过去」，所以它必须比文档本身快。
 * - context 文档 61 行给 126 帧（约 0.48 行/帧 ≈ 11.6 行/s）；思维链 27 行给 107 帧；回复 40 行给 169 帧。
 * - 回复的窗口是 `[251, 419]` **闭区间**：`design-options.md` §1「在第 419 帧完成」。
 * @type {readonly Block[]}
 */
export const BLOCKS = [
  { key: 'preamble', label: '01a 前言（滚动区）', start: 0, end: 17, lines: PREAMBLE },
  { key: 'context', label: '01b context 文档', start: 18, end: 143, lines: CONTEXT_DOC },
  {
    key: 'thinking',
    label: '02 思维链',
    start: MARKS.think,
    end: MARKS.output - 1,
    thinkBody: true,
    lines: [
      ...THINKING.slice(0, LYRIC_AT),
      ...LYRIC_LINES,
      ...THINKING.slice(LYRIC_AT),
    ],
  },
  { key: 'answer', label: '03 输出', start: MARKS.output, end: MARKS.firstLyric, lines: ANSWER },
];

/** 歌词行在 `thinking` 块里的行号（0 起）。 */
export const LYRIC_INDEX_IN_THINK = LYRIC_AT;

/** 文档总行数。 */
export const TOTAL_LINES = BLOCKS.reduce((s, b) => s + b.lines.length, 0);

/**
 * 第 `k` 行（全文档连续编号，0 起）属于哪个块、块内第几行。
 * 用一次线性扫描回答 —— 行数是几十，不值得建索引。
 * @param {number} k
 * @returns {{block: Block, index: number, thinkBodyPad: number}}
 */
export function locateLine(k) {
  let rest = k;
  for (const b of BLOCKS) {
    if (rest < b.lines.length) return { block: b, index: rest, thinkBodyPad: b.thinkBody ? THINK_BODY_PAD : 0 };
    rest -= b.lines.length;
  }
  throw new Error(`locateLine(${k}): 超出文档总行数 ${TOTAL_LINES}`);
}

// ─────────────────────────────────────────────────────────────────────────────
// 3. 逐帧的纯函数
// ─────────────────────────────────────────────────────────────────────────────

/**
 * 一个块一共多少个**字符**（行长之和）。
 * @param {Block} b
 * @returns {number}
 */
export function charsInBlock(b) {
  return b.lines.reduce((s, l) => s + l.length, 0);
}

/**
 * 一个块在第 `n` 帧已经吐出了**几个字符**。
 *
 * 映射把**两端都钉死**：`n = start` 时吐出第 1 个字，`n = end` 时吐完**最后一个字**。
 * 这是 `design-options.md` §1「输出在第 419 帧完成」唯一的实现方式 ——
 * 换成 `ceil(C·(n−s+1)/T)` 那种写法会**提前若干帧**收尾，
 * 于是「完成的那一瞬正好开词」这句话就不成立了（实测过一次：提前 4 帧）。
 *
 * ⚠️ **逐字，不是逐行。** 第一版是逐行（一行一次蹦出来），那是**我自己的简化**，不是要求：
 * 当时的理由是「逐字会破坏行网格的可证明性」。**这个理由是错的** ——
 * 一行的行盒高 24px 与它显示了多少个字符**无关**（行盒是按整行占位、用 `overflow:hidden` 裁的），
 * 所以逐字完全不影响 `内容高 = 24 × 行盒数`。
 * 作者动态检查时指出了这一点（"一行一行而不是一个字一个字"），于是改成逐字。
 *
 * 公式：`1 + floor((n−s)·(C−1)/(T−1))`，夹在 `[0, C]`；反解见 `frameOfChar()`。
 * @param {Block} b
 * @param {number} n
 * @returns {number}
 */
export function charsRevealed(b, n) {
  const C = charsInBlock(b);
  if (C <= 0) return 0;
  if (n < b.start) return 0;
  if (C === 1) return 1;
  const T = b.end - b.start + 1;
  if (n >= b.end) return C;
  const grown = 1 + Math.floor(((n - b.start) * (C - 1)) / (T - 1));
  return Math.max(0, Math.min(C, grown));
}

/**
 * @typedef {Object} Reveal
 * @property {number} full 已经完全吐出来的行数
 * @property {string} partial 正在吐的那一行的**已显示前缀**（没有则空串）
 * @property {number} partialIndex 正在吐的那一行的行号（`full`，没有则 -1）
 * @property {number} boxes 这一块当前占的**行盒数**（`full + (partial ? 1 : 0)`）—— 内容高只认它
 * @property {number} chars 已吐出的字符数
 */

/**
 * 把一个块的字符进度拆成「整行 + 半行」。
 * @param {Block} b
 * @param {number} n
 * @returns {Reveal}
 */
export function revealAt(b, n) {
  const chars = charsRevealed(b, n);
  let rem = chars;
  let full = 0;
  for (const line of b.lines) {
    if (rem >= line.length) {
      rem -= line.length;
      full++;
    } else {
      // 正在吐这一行：只显示前 rem 个字符
      return {
        full,
        partial: line.slice(0, rem),
        partialIndex: full,
        boxes: full + (rem > 0 ? 1 : 0),
        chars,
      };
    }
  }
  return { full, partial: '', partialIndex: -1, boxes: full, chars };
}

/**
 * 文档在第 `n` 帧占了**几个行盒**（全文档连续计数）—— 内容高 = 它 × 24px。
 *
 * 名字保留成 `revealedLines`（历史原因），但语义是**行盒数**：正在吐的那一行也算一个盒子。
 * @param {number} n
 * @returns {number}
 */
export function revealedLines(n) {
  let sum = 0;
  for (const b of BLOCKS) sum += revealAt(b, n).boxes;
  return sum;
}

/**
 * 第 `k` 行（0 起）的**第一个字符**出现的帧号 —— `charsRevealed()` 的反解。
 *
 * `n = start + ceil(charIndex·(T−1)/(C−1))`。
 * @param {number} k
 * @returns {number}
 */
export function frameOfLineStart(k) {
  const { block, index } = locateLine(k);
  const before = block.lines.slice(0, index).reduce((s, l) => s + l.length, 0);
  return frameOfChar(block, before);
}

/**
 * 第 `k` 行（0 起）的**最后一个字符**出现的帧号。
 * `frameOfLineStart(k+1) - 1` 与它相等，但这里直接按字符算，不依赖下一行的存在。
 * @param {number} k
 * @returns {number}
 */
export function frameOfLineDone(k) {
  const { block, index } = locateLine(k);
  const before = block.lines.slice(0, index).reduce((s, l) => s + l.length, 0);
  const last = before + Math.max(0, block.lines[index].length - 1);
  return frameOfChar(block, last);
}

/**
 * 块内第 `i` 个字符（0 起）出现的帧号。
 * @param {Block} b
 * @param {number} i
 * @returns {number}
 */
export function frameOfChar(b, i) {
  const C = charsInBlock(b);
  if (C <= 1) return b.start;
  const T = b.end - b.start + 1;
  return Math.min(b.end, Math.max(b.start, b.start + Math.ceil((i * (T - 1)) / (C - 1))));
}

/** 歌词第一行（英文那句）在文档里的全局行号。 */
export function lyricLineIndex() {
  let base = 0;
  for (const b of BLOCKS) {
    if (b.key === 'thinking') return base + LYRIC_INDEX_IN_THINK;
    base += b.lines.length;
  }
  throw new Error('BLOCKS 里没有 thinking 块');
}

/**
 * 歌词「成形」的窗口（帧，闭区间）。§1 要求它**清楚 1–2 秒**。
 *
 * 起点 = 英文那句**吐完最后一个字**的那一帧（逐字之后，"成形"的自然是吐完的那一刻）；
 * 长度取 1.5 s = 36 帧。中文那行紧随其后（约 1–2 帧），落在窗口内。
 * @param {number} [seconds]
 * @returns {{from: number, to: number, frames: number}}
 */
export function lyricWindow(seconds = 1.5) {
  const from = frameOfLineDone(lyricLineIndex());
  const frames = Math.round(seconds * FPS);
  return { from, to: from + frames - 1, frames };
}

/**
 * 歌词的「清楚度」：1 = 完全成形，0 = 和别的思维链文字一样。
 *
 * 它是 `n` 的纯函数，而且**可以给后期用**：`design-options.md` §1.6 把「糊」交给后期，
 * 后期若想让歌词那 1.5 s 少糊一点，读这个数就行，不用去猜帧号。
 * @param {number} n
 * @returns {number} 0..1
 */
export function lyricEmphasis(n) {
  const { from, to } = lyricWindow();
  if (n < from || n > to) return 0;
  const fadeIn = 4;
  const fadeOut = 8;
  if (n < from + fadeIn) return (n - from + 1) / fadeIn;
  if (n > to - fadeOut) return Math.max(0, (to - n) / fadeOut);
  return 1;
}

/**
 * 第 `n` 帧的滚动窗口高（px）。
 * 它就是「舞台高 − 固定区高 − 输入框高」，三个数都是我们自己定的，所以**不需要测量**。
 * @param {number} height 舞台高（CSS px）
 * @returns {number}
 */
export function scrollWindowHeight(height) {
  const h = height - FIXED_HEIGHT - COMPOSER_HEIGHT;
  if (h < LINE_H * 4) {
    throw new Error(
      `intro: 舞台高 ${height}px 减去固定区 ${FIXED_HEIGHT}px 与输入框 ${COMPOSER_HEIGHT}px 之后` +
        `只剩 ${h}px —— 滚动区放不下 4 行。\n` +
        `  hint: 视口高要 > ${FIXED_HEIGHT + COMPOSER_HEIGHT + LINE_H * 4}px；引子的目标矩形是 960×640`,
    );
  }
  return h;
}

/**
 * 第 `n` 帧的滚动位置（px）—— **`t` 的纯函数，且不需要任何布局测量**。
 *
 * 规则：**把最新吐出来的那一行压到窗口底部**（真实聊天窗口的 auto-follow）。
 * `scrollAtFrame(n) = max(0, 内容高(n) − 窗口高)`，而 `内容高(n) = 24 × 已显示行数 + 块内边距`。
 *
 * 于是「设了 `scrollTop` 但内容不够高、被浏览器夹住」这件事在**算术上不可能发生**：
 * 这个值**恰好就是** `maxScroll`（`scrollHeight − clientHeight`）。
 * `film/test/pages.test.js` 里有一条测试对**全片 4741 帧**验证 `want ≤ maxScroll`。
 * @param {number} n 帧号
 * @param {{height?: number}} [opts] `height` = 舞台高（CSS px），默认 640
 * @returns {number} 滚动位置（CSS px）
 */
export function scrollAtFrame(n, opts = {}) {
  const height = opts.height ?? 640;
  const win = scrollWindowHeight(height);
  const content = contentHeight(n);
  return Math.max(0, content - win);
}

/**
 * 第 `n` 帧的内容总高（px）—— 只算**已经显示的行**。
 *
 * = `24 × 已显示行数` + 思维链那块（表头一格 + `thinkBody` 的 8 px 上下内边距）。
 * 这个数**必须**等于浏览器算出来的 `scrollHeight`，`--intro-scroll-check` 就是在盯这件事。
 * @param {number} n
 * @returns {number}
 */
export function contentHeight(n) {
  const revealed = revealedLines(n);
  const think = BLOCKS.find((b) => b.key === 'thinking');
  const thinkShown = think ? revealAt(think, n).boxes : 0;
  return revealed * LINE_H + (thinkShown > 0 ? THINK_HEAD_LINES * LINE_H + THINK_BODY_PAD : 0);
}

/**
 * 一行文本的「视觉宽度」，按半角字符计（中日韩算 2）。
 * 只用来做预算检查，不参与画面。
 * @param {string} s
 * @returns {number}
 */
export function visualWidth(s) {
  let w = 0;
  for (const ch of s) {
    const c = /** @type {number} */ (ch.codePointAt(0));
    w += c >= 0x1100 && (c <= 0x115f || (c >= 0x2e80 && c <= 0xa4cf) || (c >= 0xac00 && c <= 0xd7a3) || (c >= 0xf900 && c <= 0xfaff) || (c >= 0xfe30 && c <= 0xfe6f) || (c >= 0xff00 && c <= 0xff60) || (c >= 0xffe0 && c <= 0xffe6)) ? 2 : 1;
  }
  return w;
}

/**
 * 引子的自述（报告与 `--help` 用）。
 * @returns {string}
 */
export function describe() {
  const blocks = BLOCKS.map((b) => {
    const t0 = timeAt(b.start).toFixed(3);
    const t1 = timeAt(b.end + 1).toFixed(3);
    const T = b.end - b.start + 1;
    const C = charsInBlock(b);
    const rate = ((C - 1) / Math.max(1, T - 1) * FPS).toFixed(1);
    return (
      `  ${b.label.padEnd(22)} 帧 ${String(b.start).padStart(3)}–${String(b.end).padStart(3)}  ${t0}–${t1} s` +
      `  ${String(b.lines.length).padStart(2)} 行 / ${String(C).padStart(4)} 字  ${rate} 字/s`
    );
  });
  const lw = lyricWindow();
  return [
    `引子  帧 0–${MARKS.firstLyric - 1}（${FPS} fps）· 文档 ${TOTAL_LINES} 行 · **逐字**吐出 · 行高 ${LINE_H}px · 固定区 ${FIXED_HEIGHT}px`,
    ...blocks,
    `  歌词成形           帧 ${lw.from}–${lw.to}（${(lw.frames / FPS).toFixed(2)} s，从英文那句吐完算起）`,
    `  全片               帧 0–${FRAME_COUNT - 1}`,
  ].join('\n');
}
